### ISSUE TITLE
Bonus points for specific items

### ISSUE THREAD

**Issue by hopperelec** [hopperelec/ItemRacePlugin#4]
The config should provide the option to list items and bonus points each item can get. For example:

```yml
bonuses:
  diamond:
    # Always award double points for diamonds
    - multiply: 2
    # Award an extra point for a stack of diamonds
    - add: 1
      amount: 64
  dragon_egg:
    # Award specifically 5 points for the first dragon egg deposited
    - set: 5
      amount: 1
```
